#!/bin/sh
#
# TMote Sky - testbed utils  
#

reset() {
	bsl.py -c /dev/ttyUSB0 --telosb --reset
}

start() {
	bsl.py -c /dev/ttyUSB0 --telosb --reset
}

stop() {
   	bsl.py -c /dev/ttyUSB0 --telosb --stop
}

case "$*" in
  reset)
	reset
    ;;
  start)
	start
    ;;
  stop)
	stop
    ;;
  *)
	echo "Usage: $0 {reset|start|stop of TMote Sky}"
	exit 1
esac

if [ "$error" ];then
  exit $error
fi

#exit $?

