#ifndef REMOTE_PROTOCOLS_CLIENT_SERVER_LOCALCONSTANTS_H
#define REMOTE_PROTOCOLS_CLIENT_SERVER_LOCALCONSTANTS_H

enum result_types
{
	// operation results
	SUCCESS,
	FAILURE,
	MOTE_NOT_CONTROLLED,
	MOTE_NOT_FOUND,
	MOTE_OCCUPIED,
	NOT_SUPPORTED
};

#endif
