#!/bin/sh
#
# MicaZ + MIB520 - testbed utils  
#

reset() {
	uisp -dprog=mib510 -dserial=/dev/ttyUSB1 -dpart=ATmega128 --restart
}

start() {
	uisp -dprog=mib510 -dserial=/dev/ttyUSB1 -dpart=ATmega128 --start
}

stop() {
	uisp -dprog=mib510 -dserial=/dev/ttyUSB1 -dpart=ATmega128 --stop
}

case "$*" in
  reset)
	reset
    ;;
  start)
	start
    ;;
  stop)
	stop
    ;;
  *)
	echo "Usage: $0 {reset|start|stop of MicaZ}"
	exit 1
esac

if [ "$error" ];then
  exit $error
fi

#exit $?

