#!/bin/bash
#
# diku_mch        Starts DIKU Mote Control Host
#

# Source function library.
. /etc/init.d/functions

[ -f /sbin/diku_mch ] || exit 0

RETVAL=0

umask 077

start() {
 	echo -n "Starting diku_mch: "
	daemon diku_mch --config-file=/etc/diku_mch.cfg --daemonize=1
	RETVAL=$?
	return $RETVAL
}	
stop() {
	echo -n "Shutting down diku_mch: "
	killproc diku_mch
	RETVAL=$?
	return $RETVAL
}
rhstatus() {
	status diku_mch
}
restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  status)
  	rhstatus
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	exit 1
esac

exit $?

